# Generated by Django 3.1.3 on 2021-01-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210118_1553'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('posts', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
